### ISSUE TITLE
Suggestions for fixing the sleep function in required_attention.js

### ISSUE THREAD

**Issue by Sqaaakoi** [Resurrection3387/RetinaFuture#1]
Turn it into a promise, and use setTimeout that runs the resolve function after the time specified in the first argument. Feel free to steal garbage code attached.
![image](https://user-images.githubusercontent.com/37475903/71459464-7bcd6b80-280c-11ea-969b-83f8c8730d99.png)
[wait.js but txt because github sucks](https://github.com/Resurrection3387/RetinaFuture/files/4001468/wait.js.txt)

**Comment by Sqaaakoi** [comment]
Also, for that msToTime function, parseInt is not for rounding down the numbers. Use Math.floor for that

**Comment by Resurrection3387** [comment]
Thanks! I'll take a look at your code you sent me, and, if needed, will reopen the issue.

Closed.
